"""add_cost_paid_to_posts

Revision ID: 00ace289fe2c
Revises: 9de8ec920f36
Create Date: 2026-02-14 20:28:39.954803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00ace289fe2c'
down_revision: Union[str, None] = '9de8ec920f36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('cost_paid', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'cost_paid')
    # ### end Alembic commands ###
