"""add_balance_and_ledger

Revision ID: 4a17b2b65f63
Revises: 
Create Date: 2026-02-14 19:39:56.740285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a17b2b65f63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add balance column with default so existing users get 2000 sat
    op.add_column(
        'users',
        sa.Column('available_balance', sa.BigInteger(), nullable=False, server_default='2000'),
    )
    # Clean up legacy auth columns if they exist
    try:
        op.drop_index('ix_users_email', table_name='users')
    except Exception:
        pass
    try:
        op.drop_column('users', 'password_hash')
    except Exception:
        pass
    try:
        op.drop_column('users', 'email')
    except Exception:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'available_balance')
    # ### end Alembic commands ###
