"""add_post_like_comment_like_cost_paid

Revision ID: 91d849cbbda0
Revises: 00ace289fe2c
Create Date: 2026-02-14 21:11:43.909125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d849cbbda0'
down_revision: Union[str, None] = '00ace289fe2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('cost_paid', sa.BigInteger(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'cost_paid')
    # ### end Alembic commands ###
