"""remove_bonus_add_free_posts

Revision ID: 9de8ec920f36
Revises: 4a17b2b65f63
Create Date: 2026-02-14 20:08:59.069731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9de8ec920f36'
down_revision: Union[str, None] = '4a17b2b65f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('free_posts_remaining', sa.Integer(), nullable=False, server_default='1'),
    )
    # Reset all balances to 0 (no more signup bonus)
    op.execute("UPDATE users SET available_balance = 0")
    # Clean up old bonus ledger entries
    op.execute("DELETE FROM ledger WHERE action_type IN ('signup_bonus', 'daily_login')")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'free_posts_remaining')
    # ### end Alembic commands ###
