"""add_trust_sub_scores

Revision ID: df6c5ea0bf11
Revises: bf0808e3a704
Create Date: 2026-02-14 23:00:20.261186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6c5ea0bf11'
down_revision: Union[str, None] = 'bf0808e3a704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creator_score', sa.Integer(), server_default='500', nullable=False))
    op.add_column('users', sa.Column('curator_score', sa.Integer(), server_default='500', nullable=False))
    op.add_column('users', sa.Column('juror_score', sa.Integer(), server_default='500', nullable=False))
    op.add_column('users', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'juror_score')
    op.drop_column('users', 'curator_score')
    op.drop_column('users', 'creator_score')
    # ### end Alembic commands ###
